version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data

  mongo:
    image: mongo
    ports:
      - 27017:27017

  socket:
      image: node
      ports:
        - 5000:5000

  web:
    build: .
    image: node:0.12
    working_dir: /usr/src/myapp
    volumes:
      - /src/app:/usr/src/myapp
    ports:
      - 80:3000
    links:
      - redis
      - mongo