version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./config/redis.conf:/usr/src/app/node_modules/redis-server/redis.conf
    command:
      - /usr/src/app/node_modules/redis-server/redis.conf
    ports:
      - 6379:6379

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

#  kue:
#    build: .
#    image: kue
#    command: ["npm", "run", "kue"]
#    ports:
#      - 5000:5000
#    links:
#      - redis