version: "3"

services:
  redis:
    container_name: redis
    image: redis
    command: ["sudo redis-server", "/config/redis.conf"]

  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

#  kue:
#    build: .
#    image: kue
#    command: ["npm", "run", "kue"]
#    ports:
#      - 5000:5000
#    links:
#      - redis