version: "3"

services:
  app1:
    container_name: app1
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo

  app2:
      container_name: app2
      build: .
      ports:
        - 5000:3000
      depends_on:
        - redis
        - mongo

  app3:
      container_name: app3
      build: .
      ports:
        - 4000:3000
      depends_on:
        - redis
        - mongo

  app4:
      container_name: app4
      build: .
      ports:
        - 5500:3000
      depends_on:
        - redis
        - mongo

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./config/redis.conf:/usr/src/app/node_modules/redis-server/redis.conf
    command:
      - /usr/src/app/node_modules/redis-server/redis.conf
    ports:
      - 6379:6379

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
